apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patroni-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints",
                "persistentvolumeclaims", "events",
                "configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
