apiVersion: v1
kind: Service
metadata:
  name: patroni
  namespace: app-deployment
spec:
  clusterIP: None
  selector:
    app: patroni
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: api
    port: 8008
    targetPort: 8008