
create table users
(
    user_id          bigint generated by default as identity
        primary key,
    username                   varchar(255) unique,
    password                   varchar(255),
    name                       varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table country
(
    country_id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    continent varchar(4000)
);

create table author
(
    author_id                   bigint generated by default as identity
        primary key,
    name                 varchar(255),
    surname varchar(255),
    country_id bigint references country

);

create table book
(
    book_id              bigint generated by default as identity
        primary key,
    name            varchar(255),
    category varchar(50),
    author_id     bigint references author,
    available_copies int
);

create table book_rent
(
    book_rent_id              bigint generated by default as identity
        primary key,

    user_id bigint references users,
    book_id bigint references book
);

create table wishlist
(
    user_id bigint references users,
    book_id bigint references book,
    primary key (user_id, book_id)
);