apiVersion: batch/v1
kind: Job
metadata:
  name: init-books-db
  namespace: app-deployment
spec:
  template:
    spec:
      containers:
      - name: init
        image: postgres:15
        command: ['sh', '-c', 'psql -h pgpool-service.app-deployment.svc.cluster.local 
        -U postgres -d postgres -c "CREATE DATABASE \"books-db\";"']
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
      restartPolicy: OnFailure