version: '3.8'

services:
  database:
    image: postgres:17.4
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./books-app-backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./books-app-backend/views.sql:/docker-entrypoint-initdb.d/views.sql

  backend:
    build:
      context: ./books-app-backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    links:
      - database

  frontend:
    build:
      context: ./books-app-frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_HOST: ${VITE_BACKEND_HOST}
        VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
        VITE_BACKEND_BASE_PATH: ${VITE_BACKEND_BASE_PATH}
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
