apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: danielilievskii/books-app-frontend:1.0.0
        ports:
        - containerPort: 80